### ISSUE TITLE
Add readme and example

### ISSUE THREAD

**Issue by Zxilly** [casbin-js/react-authz#2]
@Wsteth Could you please work on this?

**Comment by hsluoyz** [comment]
I think @Wsteth has quited.

**Comment by Wsteth** [comment]
@Zxilly @hsluoyz  I apologise. I've been busy with my college and job things. Maybe a few days later I will begin this again.

**Comment by bohdan-snext** [comment]
@Wsteth Any updates on this? I'd appreciate an example how to use it.

**Comment by hsluoyz** [comment]
@Zxilly can you work on it?

**Comment by Zxilly** [comment]
@hsluoyz I didn't know how this library work. I need time to read source.

**Comment by Wsteth** [comment]
@hsluoyz @Zxilly @bohdan-snext There are some errors when I pack.  It occurs packing the node-casbin's 'fs' library. It can work in the dev mode of React Apps, but the packed library cannot work. This also happens in issue#257 of node-casbin.

**Comment by Zxilly** [comment]
@Wsteth I'm not familiar with react. Will it resolve every library imported even it was not actually used?
I wrote `vue-authz` and not met this issue.

**Comment by Wsteth** [comment]
> @Wsteth I'm not familiar with react. Will it resolve every library imported even it was not actually used?
> I wrote `vue-authz` and not met this issue.

I use rolllup to pack the library and CRA to test. CRA bundles the whole imported library. The specific details I don't remember. I will use webpack to check that. If not, maybe I need to wait for the refactored node-casbin.
